baseurl = "https://treatstoeat.com/"
title = "Gay's Treats To Eat"
theme = "whiteplain"
languageCode = "en"

# Disqus shortname
# disqusShortname = "Shortname"
# google analytics tracking id
# googleAnalytics = "Toracking ID"

# Copyright notice. This is displayer in the footer.
# copyright = "&copy; Copyright 2017 Your name"

[params]
  # Date format
  dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "BK Framily"
  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

[taxonomies]
  category = "Recipe Category"
  tag = "Tags"

# Header Menu
[[menu.main]]
  name = "Recipe Category"
  identifier = "category"
  url = "/category/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2